version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_NAME=finance.db  # Use an environment variable for the database name
    volumes:
      - ./finance.db:/app/finance.db  # Persist the database file
