name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: |
        docker-compose build
        docker tag finance_management_proj_app ${{ secrets.DOCKER_USERNAME }}/finance_management_proj_app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/finance_management_proj_app:latest

    - name: Run tests
      run: docker-compose run test

    - name: Notify AWS to Start CodePipeline
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Adjust the region as necessary
      run: |
        aws codepipeline start-pipeline-execution --name finance_management_proji_pipeline
